const db = require("../db"); // Ensure this is the correct path to your database connection

const exercises = [
  {
    question: "Ich __________ in einem Büro.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "arbeite",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Welches Verkehrsmittel benutzt du für die Arbeit?",
    type: "multiple_choice",
    options: JSON.stringify(["Auto", "Fahrrad", "Bus", "Zug"]),
    correct_answer: "Auto",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Der Flug nach Berlin ist um __________ Uhr.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "15",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welches Land ist kein Nachbar von Deutschland?",
    type: "multiple_choice",
    options: JSON.stringify(["Frankreich", "Polen", "Spanien", "Dänemark"]),
    correct_answer: "Spanien",
    difficulty: 0.4,
    topic: "travel",
  },
  {
    question: "Im Hotel brauchen wir eine __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Reservierung",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "Welche Sprache spricht man in Deutschland?",
    type: "multiple_choice",
    options: JSON.stringify(["Englisch", "Spanisch", "Deutsch", "Französisch"]),
    correct_answer: "Deutsch",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Zum Frühstück esse ich __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Brötchen",
    difficulty: 0.2,
    topic: "general",
  },
  {
    question: "Welches Wort bedeutet „Danke“ auf Deutsch?",
    type: "multiple_choice",
    options: JSON.stringify(["Bitte", "Hallo", "Danke", "Tschüss"]),
    correct_answer: "Danke",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Ich möchte eine Fahrkarte nach __________ kaufen.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "München",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "Welches dieser Wörter beschreibt eine Arbeitsstelle?",
    type: "multiple_choice",
    options: JSON.stringify(["Schule", "Büro", "Kino", "Hotel"]),
    correct_answer: "Büro",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Ich fahre jeden Morgen mit dem __________ zur Arbeit.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Bus",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Was brauchst du, um ein Flugticket zu kaufen?",
    type: "multiple_choice",
    options: ["Reisepass", "Schlüssel", "Handtuch", "Buch"],
    correct_answer: "Reisepass",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "Mein Chef ist sehr __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "freundlich",
    difficulty: 0.4,
    topic: "work",
  },
  {
    question:
      "Welches Dokument brauchst du für die Einreise in ein anderes Land?",
    type: "multiple_choice",
    options: ["Fahrkarte", "Reisepass", "Geldschein", "Visitenkarte"],
    correct_answer: "Reisepass",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "Am Wochenende mache ich gerne einen __________ im Park.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Spaziergang",
    difficulty: 0.2,
    topic: "general",
  },
  {
    question: "Wo gehst du hin, wenn du Lebensmittel kaufen möchtest?",
    type: "multiple_choice",
    options: ["Supermarkt", "Apotheke", "Bibliothek", "Tankstelle"],
    correct_answer: "Supermarkt",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Ich arbeite als __________ in einem Krankenhaus.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Arzt",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Welche dieser Städte liegt nicht in Deutschland?",
    type: "multiple_choice",
    options: ["Berlin", "Hamburg", "Wien", "Köln"],
    correct_answer: "Wien",
    difficulty: 0.4,
    topic: "travel",
  },
  {
    question: "Der Bus fährt um __________ Uhr ab.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "8",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welche Farbe hat die deutsche Fahne?",
    type: "multiple_choice",
    options: ["Rot-Weiß-Blau", "Schwarz-Rot-Gold", "Grün-Gelb", "Blau-Weiß"],
    correct_answer: "Schwarz-Rot-Gold",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Ich __________ meine Kollegen im Büro.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "treffe",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Welches dieser Wörter bedeutet 'Flughafen'?",
    type: "multiple_choice",
    options: ["Bahnhof", "Flughafen", "Tankstelle", "Supermarkt"],
    correct_answer: "Flughafen",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Ich buche ein __________ für meine Geschäftsreise.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Hotelzimmer",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Was brauchst du, um in einem Hotel einzuchecken?",
    type: "multiple_choice",
    options: ["Schlüssel", "Pass", "Buch", "Tasche"],
    correct_answer: "Pass",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "In Deutschland gibt man oft __________ als Begrüßung.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "die Hand",
    difficulty: 0.2,
    topic: "general",
  },
  {
    question: "Welches dieser Lebensmittel gehört nicht zum Frühstück?",
    type: "multiple_choice",
    options: ["Brötchen", "Kaffee", "Bleistift", "Marmelade"],
    correct_answer: "Bleistift",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Mein Arbeitsplatz ist im __________ Stock.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "dritten",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Welches Land grenzt nicht an Deutschland?",
    type: "multiple_choice",
    options: ["Österreich", "Schweiz", "Italien", "Frankreich"],
    correct_answer: "Italien",
    difficulty: 0.4,
    topic: "travel",
  },
  {
    question: "Ich packe meine __________ für die Reise.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Koffer",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welche dieser Städte ist die Hauptstadt von Deutschland?",
    type: "multiple_choice",
    options: ["München", "Hamburg", "Berlin", "Frankfurt"],
    correct_answer: "Berlin",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Ich __________ jeden Morgen um 8 Uhr zur Arbeit.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "fahre",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Welches Verkehrsmittel benutzt man für eine Geschäftsreise?",
    type: "multiple_choice",
    options: ["Fahrrad", "Auto", "Flugzeug", "Bus"],
    correct_answer: "Flugzeug",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Ich brauche eine __________, um ins Ausland zu reisen.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Reisepass",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welches dieser Wörter bedeutet 'Gepäck'?",
    type: "multiple_choice",
    options: ["Tasche", "Koffer", "Rucksack", "Handschuh"],
    correct_answer: "Koffer",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Am Wochenende gehe ich oft ins __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Kino",
    difficulty: 0.2,
    topic: "general",
  },
  {
    question: "Welches dieser Lebensmittel isst man oft zum Mittagessen?",
    type: "multiple_choice",
    options: ["Brötchen", "Suppe", "Kaffee", "Tee"],
    correct_answer: "Suppe",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Meine Arbeit beginnt um __________ Uhr morgens.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "neun",
    difficulty: 0.3,
    topic: "work",
  },
  {
    question: "Welches dieser Länder spricht Deutsch als offizielle Sprache?",
    type: "multiple_choice",
    options: ["Spanien", "Schweiz", "Italien", "Frankreich"],
    correct_answer: "Schweiz",
    difficulty: 0.4,
    topic: "general",
  },
  {
    question: "Ich nehme den __________ zum Flughafen.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Zug",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welcher dieser Orte ist kein Arbeitsplatz?",
    type: "multiple_choice",
    options: ["Büro", "Supermarkt", "Schule", "Strand"],
    correct_answer: "Strand",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Ich arbeite in einem __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Büro",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Welches dieser Dinge findet man in einem Büro?",
    type: "multiple_choice",
    options: ["Tafel", "Schreibtisch", "Bett", "Herd"],
    correct_answer: "Schreibtisch",
    difficulty: 0.2,
    topic: "work",
  },
  {
    question: "Wir fahren im Sommer in den __________.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Urlaub",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welches dieser Wörter bedeutet 'Flugticket'?",
    type: "multiple_choice",
    options: ["Bordkarte", "Fahrkarte", "Reisepass", "Gepäck"],
    correct_answer: "Bordkarte",
    difficulty: 0.3,
    topic: "travel",
  },
  {
    question: "Ich bestelle eine __________ im Restaurant.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Pizza",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Welches dieser Getränke ist heiß?",
    type: "multiple_choice",
    options: ["Wasser", "Kaffee", "Limonade", "Cola"],
    correct_answer: "Kaffee",
    difficulty: 0.1,
    topic: "general",
  },
  {
    question: "Ich __________ jeden Morgen um 7 Uhr auf.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "stehe",
    difficulty: 0.3,
    topic: "general",
  },
  {
    question: "Welches dieser Wörter beschreibt einen Verkehrsmittel?",
    type: "multiple_choice",
    options: ["Flughafen", "Taxi", "Hotel", "Restaurant"],
    correct_answer: "Taxi",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Ich brauche eine __________, um in der Stadt Bus zu fahren.",
    type: "fill_in_the_blank",
    options: null,
    correct_answer: "Fahrkarte",
    difficulty: 0.2,
    topic: "travel",
  },
  {
    question: "Welches dieser Dinge gehört nicht zu einem Büro?",
    type: "multiple_choice",
    options: ["Computer", "Telefon", "Waschmaschine", "Drucker"],
    correct_answer: "Waschmaschine",
    difficulty: 0.3,
    topic: "work",
  },
];

const seedExercises = async () => {
  try {
    await db("exercises").insert(exercises);
    console.log("✅ Exercises seeded successfully.");
  } catch (error) {
    console.error("❌ Error inserting exercises:", error);
  } finally {
    process.exit();
  }
};

seedExercises();
